name: Publish Workspace

on:
  push:
    branches:
      - main
    paths:
      - "docs"

jobs:
  publish:
    name: Publish structurizr workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: structurizr-cli action
        uses: aidmax/structurizr-cli-action@v0.2.0
        with:
          id: ${{ secrets.WORKSPACE_ID }}
          key: ${{ secrets.API_KEY }}
          secret: ${{ secrets.API_SECRET }}
          workspace: workspace.dsl
